---
image:  docker-unrar
version: v1.1.15
name: Unrar to reuse on other containters
description: "[docker-unrar] Unrar to reuse on other containters for chukyserver.io"
ext_release: "7.2.3"
arch:
  - aarch64
  - x86_64
  - armv7
